<?php require "includes.php"; ?>
<!doctype html><html lang="id"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>HMPSIF|Himpunan Mahasiswa Prodi Teknik Informatika</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" rel="stylesheet"><link href="assets/css/style_modern.css" rel="stylesheet"></head>
<body>
<nav class="navbar navbar-expand-lg sticky-top"><div class="container"><a class="navbar-brand" href="index.php" style="display:flex;align-items:center;padding:0;"> <img src="assets/img/logo1.png" alt="HMPSIF" style="width:120px !important;height:45px !important;max-width:120px !important;max-height:45px !important;object-fit:contain !important;display:block !important;" > </a> <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="nav"><ul class="navbar-nav ms-auto align-items-lg-center">
<li class="nav-item"><a class="nav-link" href="index.php">Home</a></li><li class="nav-item"><a class="nav-link" href="tentang.php">Tentang</a></li><li class="nav-item"><a class="nav-link" href="organisasi.php">Organisasi</a></li><li class="nav-item"><a class="nav-link" href="program.php">Program Kerja</a></li><li class="nav-item"><a class="nav-link" href="kegiatan.php">Kegiatan</a></li><li class="nav-item"><a class="nav-link" href="berita.php">Berita</a></li><li class="nav-item"><a class="nav-link" href="galeri.php">Galeri</a></li><li class="nav-item"><a class="nav-link" href="gabung.php">Cara Bergabung</a></li><li class="nav-item"><a class="nav-link" href="kontak.php">Kontak</a></li>
<li class="nav-item ms-lg-2"><button id="themeToggle" class="btn btn-sm btn-outline-secondary"><i class="fa-solid fa-moon"></i></button></li><li class="nav-item ms-lg-2"><a class="btn btn-primary rounded-pill px-4" href="gabung.php">Gabung Himpunan</a></li></ul></div></div></nav>
<header class="hero position-relative"><div class="hero-shape"> <img src="assets/img/logo1.png"> </div><div class="container position-relative"><div class="row align-items-center"><div class="col-lg-8 fade-up">
<div class="eyebrow mb-3">Himpunan Mahasiswa Prodi Teknik Informatika</div><h1>Bersama HMPSIF, Berkarya, Berinovasi, dan Berdampak.</h1><p class="lead text-secondary mt-4">Ruang kolaborasi mahasiswa Teknik Informatika untuk bertumbuh, membangun kompetensi, dan menghadirkan karya yang bermanfaat bagi kampus serta masyarakat.</p><div class="d-flex gap-2 flex-wrap mt-4"><a class="btn btn-primary btn-lg rounded-pill px-4" href="tentang.php">Kenal Kami <i class="fa-solid fa-arrow-right ms-2"></i></a><a class="btn btn-outline-dark btn-lg rounded-pill px-4" href="gabung.php">Gabung Sekarang</a></div></div></div></div></header>
<section class="section"><div class="container"><div class="row g-4">
<?php foreach([["45+","Anggota"],["6","Program Kerja"],["3","Agenda"],["2014","Tahun Berdiri"]] as $s): ?><div class="col-6 col-lg-3"><div class="stat text-center fade-up"><h3><?=e($s[0])?></h3><p class="mb-0 text-muted"><?=$s[1]?></p></div></div><?php endforeach;?>
</div></div></section>
<section class="section bg-light"><div class="container"><div class="row g-5 align-items-center"><div class="col-lg-5"><div class="eyebrow">Sambutan Ketua</div><h2 class="section-title mt-2">Tempat untuk bertumbuh bersama.</h2></div><div class="col-lg-7"><p style="text-align: justify;">“Melalui website ini, kami berupaya menghadirkan informasi mengenai berbagai kegiatan, program kerja, prestasi serta informasi lainnya yang berkaitan dengan HMPSIF. Kami berharap website ini dapat menjadi sarana komunikasi dan informasi yang terbuka, mudah diakses, serta memberikan manfaat bagi seluruh mahasiswa.  
<p style="text-align: justify;"> Mari bersama-sama menjadikan HMPSIF sebagai rumah untuk bertumbuh, tempat untuk belajar, dan ruang untuk menciptakan karya. Karena setiap proses, sekecil apapun, akan menjadi bagian dari perjalanan kita dalam membangun masa depan yang lebih baik.”</p><strong class="text-muted">Sintia Nur Mala Dewi</strong><div class="text-muted">Ketua HMPSIF Periode 2026/2027</div></div></div></div></section>
<section class="section"><div class="container"><div class="d-flex justify-content-between align-items-end mb-4"><div><div class="eyebrow">Unggulan</div><h2 class="section-title">Program Kerja</h2></div><a href="program.php">Lihat semua →</a></div><div class="row g-4">
<?php $programs=$pdo->query("SELECT * FROM program_kerja ORDER BY id DESC LIMIT 3")->fetchAll(); foreach($programs as $p): ?><div class="col-md-4"><div class="card card-modern overflow-hidden"><img class="program-img" src="<?=e($p["banner"] ?: "assets/img/placeholder.jpg")?>"><div class="card-body p-4"><span class="badge badge-soft"><?=e($p["status"])?></span><h5 class="mt-3"><?=e($p["nama"])?></h5><p class="text-muted"><?=e($p["deskripsi"])?></p><a href="detail-program.php?id=<?=$p["id"]?>" class="btn btn-sm btn-outline-primary rounded-pill">Detail</a></div></div></div><?php endforeach;?></div></div></section>
<section class="section bg-light"><div class="container"><div class="row g-4 align-items-center"><div class="col-lg-7"><div class="eyebrow">Mari berkontribusi</div><h2 class="section-title">Punya ide? Bangun bersama HMPSIF.</h2><p class="text-muted">Bergabung dalam lingkungan organisasi yang mendorong kolaborasi, kompetensi, dan kontribusi nyata.</p></div><div class="col-lg-5 text-lg-end"><a class="btn btn-primary btn-lg rounded-pill" href="gabung.php">Daftar Sekarang</a></div></div></div></section>
<footer class="py-5"><div class="container"><div class="row g-4"><div class="col-lg-5"><h5 class="text-white">HMPSIF</h5><p>Himpunan Mahasiswa Prodi Teknik Informatika</p><p class="mb-0">“Berorganisasi, Berkarya, dan Berkontribusi.”</p></div><div class="col"><h6 class="text-white">Navigasi</h6><a class="footer-link d-block" href="tentang.php">Tentang Kami</a><a class="footer-link d-block" href="program.php">Program Kerja</a><a class="footer-link d-block" href="berita.php">Berita</a></div><div class="col"><h6 class="text-white">Kontak</h6><p class="mb-1"> hmpsif@unisnu.ac.id</p><p>+62 882-0075-6878 </p></div></div><hr><small>© <span id="year"></span> HMPSIF. All rights reserved. By: Nauval Hibrizi Hakim</small></div></footer><button id="backTop" class="btn btn-primary rounded-circle"><i class="fa-solid fa-arrow-up"></i></button>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="assets/js/app.js"></script></body></html>